name = "n8n-worker"
main = "src/index.js"
compatibility_date = "2024-03-08"

[build]
command = "npm install"

[[kv_namespaces]]
binding = "N8N_KV"
id = "n8n-storage"

[vars]
N8N_ENCRYPTION_KEY = "your-encryption-key-here" 